name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-jar-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build the JAR file with Maven
        run: mvn clean install

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tanapoln
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/tanapoln/sit-swtc-shopapi:${{ github.sha }}
